// Skenario roleplay untuk Hanashite Room (AI Speaking Simulator).
// `free: true` artinya bisa diakses semua user yang sudah login (1 skenario teaser).
// Sisanya hanya untuk Pro.

export type Scenario = {
  id: string;
  emoji: string;
  free: boolean;
  // Indonesian copy
  title_id: string;
  situation_id: string;
  role_id: string;
  tone_id: string;
  opening_id: string; // initial AI line shown as hint (Indonesian explanation)
  // English copy
  title_en: string;
  situation_en: string;
  role_en: string;
  tone_en: string;
  opening_en: string;
  // What the AI says first (in Japanese)
  ai_first_japanese: string;
  ai_first_romaji: string;
  // System prompt fragment describing the AI persona
  persona: string;
};

export const SCENARIOS: Scenario[] = [
  {
    id: "sc_ramen",
    emoji: "🍜",
    free: true,
    title_id: "Pesan Ramen di Ichiraku",
    situation_id: "Kamu masuk ke kedai ramen kecil di Tokyo. Pelayan menyambutmu.",
    role_id: "Pelayan toko ramen",
    tone_id: "Sopan standar (です/ます)",
    opening_id: "Pelayan akan menyapa. Pesan ramen dan minuman sesukamu.",
    title_en: "Order Ramen at Ichiraku",
    situation_en: "You enter a small ramen shop in Tokyo. The waiter greets you.",
    role_en: "Ramen shop waiter",
    tone_en: "Standard polite (desu/masu)",
    opening_en: "The waiter will greet you. Order ramen and a drink.",
    ai_first_japanese: "いらっしゃいませ！何名様ですか？",
    ai_first_romaji: "Irasshaimase! Nan-mei-sama desu ka?",
    persona:
      "You are a friendly waiter at a small ramen shop in Tokyo. Use standard polite Japanese (desu/masu form). Keep replies short (1-2 sentences). Stay in character. Offer menu items (tonkotsu, shoyu, miso, shio ramen, gyoza, beer, ocha) naturally. End the conversation politely when the order is complete.",
  },
  {
    id: "sc_meeting",
    emoji: "💼",
    free: false,
    title_id: "Meeting Pagi di Kantor",
    situation_id: "Atasanmu (shachou) memintamu melaporkan progres proyek pagi ini.",
    role_id: "Atasan (Shachou)",
    tone_id: "Keigo / Sonkeigo",
    opening_id: "Atasanmu menyapa. Berikan laporan singkat dengan keigo.",
    title_en: "Morning Meeting at the Office",
    situation_en: "Your boss (shachou) asks for your project progress this morning.",
    role_en: "Boss (Shachou)",
    tone_en: "Keigo / Sonkeigo",
    opening_en: "Your boss greets you. Give a brief report using keigo.",
    ai_first_japanese: "おはようございます。今週のプロジェクトの進捗を教えてください。",
    ai_first_romaji: "Ohayou gozaimasu. Konshuu no purojekuto no shinchoku wo oshiete kudasai.",
    persona:
      "You are a strict but fair Japanese company president (shachou) in a morning meeting. Use sonkeigo/keigo. Expect the user to use kenjougo (humble form) when referring to themselves. Ask follow-up questions about deadlines, blockers, and next steps. Keep replies concise (1-2 sentences). If the user uses casual form, gently correct them in-character.",
  },
  {
    id: "sc_shibuya",
    emoji: "🗺️",
    free: false,
    title_id: "Tersesat di Shibuya",
    situation_id: "Kamu tersesat di sekitar stasiun Shibuya dan bertanya pada orang asing.",
    role_id: "Orang asing yang ramah",
    tone_id: "Sopan standar",
    opening_id: "Orang itu akan menyapa. Tanyakan arah ke Hachiko atau tujuan lain.",
    title_en: "Lost in Shibuya",
    situation_en: "You are lost near Shibuya station and ask a stranger for help.",
    role_en: "Friendly local stranger",
    tone_en: "Standard polite",
    opening_en: "The stranger greets you. Ask for directions to Hachiko or another spot.",
    ai_first_japanese: "あ、どうしましたか？道に迷われましたか？",
    ai_first_romaji: "A, doushimashita ka? Michi ni mayowaremashita ka?",
    persona:
      "You are a kind Tokyo local near Shibuya station helping a tourist. Use standard polite Japanese. Give clear directions referencing real Shibuya landmarks (Hachiko statue, Shibuya Scramble, 109 building, Center-gai, JR line). Keep replies short (1-3 sentences). Be patient and encouraging.",
  },
  {
    id: "sc_konbini",
    emoji: "🏪",
    free: false,
    title_id: "Belanja di Konbini",
    situation_id: "Kamu membeli onigiri, kopi, dan kit kesehatan di Lawson pada tengah malam.",
    role_id: "Karyawan konbini",
    tone_id: "Sopan standar + tembakan singkat",
    opening_id: "Karyawan menyapa. Tanyakan apakah ada barang tanpa kena cukai.",
    title_en: "Shopping at a Konbini",
    situation_en: "You buy onigiri, coffee, and health supplies at a Lawson at midnight.",
    role_en: "Konbini clerk",
    tone_en: "Standard polite + quick banter",
    opening_en: "The clerk greets you. Ask if you need chopsticks, a spoon, or a microwave.",
    ai_first_japanese: "いらっしゃいませ。お箸はいりますか？",
    ai_first_romaji: "Irasshaimase. O-hashi wa irimasu ka?",
    persona:
      "You are a cheerful late-shift clerk at a Lawson konbini in Tokyo. Use standard polite Japanese with short, efficient phrases typical of konbini interactions. Ask about chopsticks, microwaving food, point cards, and offer the receipt. Keep replies very brief (1 sentence).",
  },
  {
    id: "sc_hotel",
    emoji: "🏨",
    free: false,
    title_id: "Check-in di Hotel Kyoto",
    situation_id: "Kamu tiba di ryokan tradisional di Kyoto untuk check-in dan tanya fasilitas onsen.",
    role_id: "Resepsionis hotel",
    tone_id: "Keigo sopan",
    opening_id: "Resepsionis menyapa. Berikan nama booking dan tanyakan jam makan malam.",
    title_en: "Check-in at a Kyoto Hotel",
    situation_en: "You arrive at a traditional ryokan in Kyoto to check in and ask about the onsen.",
    role_en: "Hotel front desk clerk",
    tone_en: "Polite keigo",
    opening_en: "The clerk greets you. Give your booking name and ask about dinner time.",
    ai_first_japanese: "お泊まりですか？お名前をお願いいたします。",
    ai_first_romaji: "O-tomari desu ka? O-namae wo onegai itashimasu.",
    persona:
      "You are a polite front desk clerk at a traditional ryokan in Kyoto. Use keigo (sonkeigo/kenjougo). Explain room features, onsen hours, yukata availability, and breakfast/dinner times. Be warm and hospitable. Keep replies concise (1-2 sentences).",
  },
  {
    id: "sc_izakaya",
    emoji: "🍺",
    free: false,
    title_id: "Mabuk di Izakaya",
    situation_id: "Kamu dan teman-teman masuk ke izakaya setelah kerja. Pesan otsumami dan bir.",
    role_id: "Pelayan izakaya",
    tone_id: "Kasar ramah (teineigo ringan)",
    opening_id: "Pelayan sambut dengan energik. Pesan makanan dan minuman untuk meja.",
    title_en: "Night Out at an Izakaya",
    situation_en: "You and coworkers enter an izakaya after work. Order food and drinks for the table.",
    role_en: "Izakaya server",
    tone_en: "Friendly casual (light teineigo)",
    opening_en: "The server greets you energetically. Order drinks and otsumami for the group.",
    ai_first_japanese: "いらっしゃい！何人ですか？",
    ai_first_romaji: "Irasshai! Nan-nin desu ka?",
    persona:
      "You are an energetic izakaya server in Tokyo. Use friendly, slightly casual polite Japanese (not full keigo). Recommend popular items like edamame, karaage, yakitori, and highballs. Ask about smoking/non-smoking seating. Keep replies short and energetic (1-2 sentences).",
  },
  {
    id: "sc_train",
    emoji: "🚃",
    free: false,
    title_id: "Beli Tiket Keisei Skyliner",
    situation_id: "Kamu di Stasiun Narita Airport ingin beli tiket kereta cepat ke Tokyo.",
    role_id: "Petugas loket",
    tone_id: "Sopan standar",
    opening_id: "Petugas menyapa. Tanya tiket satu arah atau pulang pergi, kelas, dan kursi.",
    title_en: "Buy a Keisei Skyliner Ticket",
    situation_en: "You're at Narita Airport Station buying an express train ticket to Tokyo.",
    role_en: "Ticket counter clerk",
    tone_en: "Standard polite",
    opening_en: "The clerk greets you. Ask about one-way or round-trip, class, and seat preference.",
    ai_first_japanese: "いらっしゃいませ。どちらまでですか？",
    ai_first_romaji: "Irasshaimase. Dochira made desu ka?",
    persona:
      "You are a ticket counter clerk at Narita Airport Station. Use standard polite Japanese. Ask destination, ticket type (one-way/round-trip), class (ordinary/green), and reserved seat. Mention the Keisei Skyliner and Narita Express options. Keep replies concise (1-2 sentences).",
  },
  {
    id: "sc_clinic",
    emoji: "🏥",
    free: false,
    title_id: "Sakit Perut di Klinik",
    situation_id: "Kamu datang ke klinik kecil karena sakit perut dan mau ambil obat.",
    role_id: "Dokter klinik",
    tone_id: "Sopan + jelas (medis)",
    opening_id: "Dokter tanya keluhan. Jelaskan gejala dan riwayat alergi.",
    title_en: "Stomachache at a Local Clinic",
    situation_en: "You visit a small clinic for stomach pain and need a prescription.",
    role_en: "Clinic doctor",
    tone_en: "Polite + clear (medical)",
    opening_en: "The doctor asks about symptoms. Describe your pain and any allergies.",
    ai_first_japanese: "どうしましたか？お腹の具合が悪いですか？",
    ai_first_romaji: "Doushimashita ka? Onaka no guai ga warui desu ka?",
    persona:
      "You are a kind clinic doctor in Japan. Use polite, clear Japanese. Ask about symptoms, duration, pain level, allergies, and medication history. Explain the diagnosis and prescription simply. Keep replies to 1-3 sentences. Use standard medical vocabulary.",
  },
  {
    id: "sc_salon",
    emoji: "💇",
    free: false,
    title_id: "Potong Rambut di Tokyo",
    situation_id: "Kamu ke salon rambut di Shinjuku dan mau potong + pewarna coklat.",
    role_id: "Hair stylist",
    tone_id: "Sopan + santai",
    opening_id: "Stylist sapa. Tunjukkan foto referensi dan diskusikan gaya.",
    title_en: "Haircut in Shinjuku",
    situation_en: "You visit a hair salon in Shinjuku for a cut and brown dye.",
    role_en: "Hair stylist",
    tone_en: "Polite + relaxed",
    opening_en: "The stylist greets you. Show a reference photo and discuss the style.",
    ai_first_japanese: "いらっしゃいませ。今日はどのようにしますか？",
    ai_first_romaji: "Irasshaimase. Kyou wa dono you ni shimasu ka?",
    persona:
      "You are a trendy hair stylist in Shinjuku. Use polite but relaxed Japanese. Ask about desired length, color, and style. Suggest options if the user is unsure. Discuss shampoo and treatment add-ons. Keep replies friendly and concise (1-2 sentences).",
  },
  {
    id: "sc_yuubin",
    emoji: "📮",
    free: false,
    title_id: "Kirim Paket ke Rumah",
    situation_id: "Kamu ke kantor pos mengirim paket besar ke Osaka dengan asuransi.",
    role_id: "Petugas kantor pos",
    tone_id: "Sopan standar",
    opening_id: "Petugas menyapa. Jelaskan isi paket, berat, dan tanya layanan.",
    title_en: "Send a Parcel Home",
    situation_en: "You visit a post office to send a large package to Osaka with insurance.",
    role_en: "Post office clerk",
    tone_en: "Standard polite",
    opening_en: "The clerk greets you. Explain the package contents, weight, and desired service.",
    ai_first_japanese: "いらっしゃいませ。何をお出ししましょうか？",
    ai_first_romaji: "Irasshaimase. Nani wo o-dashi shimashou ka?",
    persona:
      "You are a helpful post office clerk in Japan. Use standard polite Japanese. Ask about package contents, destination, shipping speed (regular/express), and whether insurance is needed. Mention available box sizes and prices. Keep replies brief (1-2 sentences).",
  },
  {
    id: "sc_ginkou",
    emoji: "🏦",
    free: false,
    title_id: "Buka Rekening Bank",
    situation_id: "Kamu ke bank lokal untuk membuka rekening tabungan sebagai pelajar asing.",
    role_id: "Petugas bank",
    tone_id: "Keigo sopan",
    opening_id: "Petugas bank menyapa. Jelaskan tujuan dan tanyakan dokumen.",
    title_en: "Open a Bank Account",
    situation_en: "You visit a local bank to open a savings account as a foreign student.",
    role_en: "Bank clerk",
    tone_en: "Polite keigo",
    opening_en: "The bank clerk greets you. Explain your purpose and ask about required documents.",
    ai_first_japanese: "いらっしゃいませ。本日はどのようなご用件でしょうか？",
    ai_first_romaji: "Irasshaimase. Honjitsu wa dono you na go-youken deshou ka?",
    persona:
      "You are a professional bank clerk at a Japanese bank. Use polite keigo. Explain required documents (residence card, hanko, phone number), account types, and debit card options. Speak clearly and patiently. Keep replies to 1-2 sentences.",
  },
  {
    id: "sc_apato",
    emoji: "🏠",
    free: false,
    title_id: "Cari Apartemen di Tokyo",
    situation_id: "Kamu bertemu agen properti untuk melihat apartemen 1K di daerah Shinjuku.",
    role_id: "Agen properti (fudousan)",
    tone_id: "Sopan ramah",
    opening_id: "Agen sapa dan tanya budget, area, dan preferensi dekat stasiun.",
    title_en: "Apartment Hunting in Tokyo",
    situation_en: "You meet a real estate agent to view a 1K apartment near Shinjuku.",
    role_en: "Real estate agent (fudousan)",
    tone_en: "Polite and friendly",
    opening_en: "The agent greets you and asks about budget, area, and station proximity preference.",
    ai_first_japanese: "こんにちは。ご予算とエリアはお決まりですか？",
    ai_first_romaji: "Konnichiwa. Go-yosan to eria wa okimari desu ka?",
    persona:
      "You are a friendly real estate agent (fudousan) in Tokyo. Use polite, friendly Japanese. Ask about budget, desired area, distance from station, and amenities (AC, washing machine space, internet). Explain key money, deposit, and rent terms. Keep replies to 1-2 sentences.",
  },
  {
    id: "sc_interview",
    emoji: "🤝",
    free: false,
    title_id: "Wawancara Kerja Part-time",
    situation_id: "Kamu wawancara untuk kerja paruh waktu di restoran cepat saji di Akihabara.",
    role_id: "Manajer toko",
    tone_id: "Sopan bisnis",
    opening_id: "Manajer sapa. Jawab pertanyaan motivasi dan jadwal.",
    title_en: "Part-time Job Interview",
    situation_en: "You interview for a part-time job at a fast-food restaurant in Akihabara.",
    role_en: "Store manager",
    tone_en: "Business polite",
    opening_en: "The manager greets you. Answer questions about motivation and availability.",
    ai_first_japanese: "本日はお越しいただきありがとうございます。まず自己紹介をお願いします。",
    ai_first_romaji: "Honjitsu wa o-koshi itadaki arigatou gozaimasu. Mazu jiko-shoukai wo onegai shimasu.",
    persona:
      "You are a fast-food store manager conducting a part-time job interview. Use business-polite Japanese. Ask about motivation, past experience, availability, and transportation. Keep replies formal but warm (1-2 sentences).",
  },
  {
    id: "sc_restoran",
    emoji: "🍽️",
    free: false,
    title_id: "Reservasi Restoran Fine Dining",
    situation_id: "Kamu telepon restoran sushi omakase untuk reservasi 2 orang hari Jumat malam.",
    role_id: "Resepsionis restoran",
    tone_id: "Keigo sangat sopan",
    opening_id: "Resepsionis angkat telepon. Jelaskan jumlah orang, tanggal, dan alergi.",
    title_en: "Fine Dining Restaurant Reservation",
    situation_en: "You call a sushi omakase restaurant to book a table for 2 on Friday night.",
    role_en: "Restaurant reservationist",
    tone_en: "Very polite keigo",
    opening_en: "The reservationist answers. Explain party size, date, and any allergies.",
    ai_first_japanese: "もしもし、寿司田でございます。ご予約ですか？",
    ai_first_romaji: "Moshi moshi, Sushi-den de gozaimasu. Go-yoyaku desu ka?",
    persona:
      "You are a reservationist at an upscale sushi omakase restaurant. Use very polite keigo. Ask about party size, date, time, allergies, and course preference. Mention cancellation policy. Keep replies extremely polite and concise (1-2 sentences).",
  },
  {
    id: "sc_immigration",
    emoji: "🛂",
    free: false,
    title_id: "Imigrasi Bandara Narita",
    situation_id: "Petugas imigrasi tanya tujuan, lama tinggal, dan tujuan kedatanganmu ke Jepang.",
    role_id: "Petugas imigrasi",
    tone_id: "Sopan resmi",
    opening_id: "Petugas memanggil. Jawab pertanyaan dengan tenang dan jelas.",
    title_en: "Narita Airport Immigration",
    situation_en: "The immigration officer asks about your purpose, length of stay, and plans in Japan.",
    role_en: "Immigration officer",
    tone_en: "Official polite",
    opening_en: "The officer calls you forward. Answer calmly and clearly.",
    ai_first_japanese: "パスポートをお願いします。日本に来た目的は何ですか？",
    ai_first_romaji: "Pasupooto wo onegai shimasu. Nihon ni kita mokuteki wa nan desu ka?",
    persona:
      "You are an immigration officer at Narita Airport. Use official but polite Japanese. Ask about purpose of visit, length of stay, accommodation address, and occupation. Keep replies short and direct (1 sentence).",
  },
  {
    id: "sc_shopping",
    emoji: "🛍️",
    free: false,
    title_id: "Beli Baju di Uniqlo",
    situation_id: "Kamu ke toko Uniqlo di Ginza mencari ukuran M dan tanya lokasi fitting room.",
    role_id: "Karyawan toko",
    tone_id: "Sopan standar",
    opening_id: "Karyawan sapa. Tanyakan ukuran, warna, dan coba baju.",
    title_en: "Clothes Shopping at Uniqlo",
    situation_en: "You visit Uniqlo in Ginza looking for size M and ask about the fitting room.",
    role_en: "Store clerk",
    tone_en: "Standard polite",
    opening_en: "The clerk greets you. Ask about size, color, and where to try items on.",
    ai_first_japanese: "いらっしゃいませ。何かお探しですか？",
    ai_first_romaji: "Irasshaimase. Nanika o-sagashi desu ka?",
    persona:
      "You are a store clerk at a Uniqlo in Ginza. Use standard polite Japanese. Ask what the customer is looking for, suggest sizes and colors, and direct them to the fitting room. Mention current promotions. Keep replies to 1-2 sentences.",
  },
  {
    id: "sc_onsen",
    emoji: "♨️",
    free: false,
    title_id: "Pengalaman Pertama di Onsen",
    situation_id: "Kamu ke onsen tradisional di Hakone dan tanya prosedur mandi kepada staf.",
    role_id: "Staf onsen",
    tone_id: "Sopan ramah",
    opening_id: "Staf jelaskan aturan onsen: cuci badan dulu, tidak pakai handuk di air, dll.",
    title_en: "First Time at an Onsen",
    situation_en: "You visit a traditional onsen in Hakone and ask staff about bathing procedures.",
    role_en: "Onsen staff",
    tone_en: "Polite and friendly",
    opening_en: "Staff explains onsen rules: wash first, no towel in water, etc.",
    ai_first_japanese: "いらっしゃいませ。お風呂はあちらです。手順をご説明しますね。",
    ai_first_romaji: "Irasshaimase. O-furo wa achira desu. Tejun wo go-setsumei shimasu ne.",
    persona:
      "You are a warm onsen staff member in Hakone. Use polite, friendly Japanese. Explain bathing etiquette (wash before entering, no towels in water, no swimming, tattoo rules). Answer questions about water temperature and rotenburo. Keep replies friendly and concise (1-2 sentences).",
  },
  {
    id: "sc_karaoke",
    emoji: "🎤",
    free: false,
    title_id: "Booking Karaoke Hingga Tengah Malam",
    situation_id: "Kamu dan teman booking ruang karaoke 3 jam pakai free drink bar.",
    role_id: "Staf karaoke",
    tone_id: "Sopan + energik",
    opening_id: "Staf tanya durasi, jumlah orang, dan pilih paket.",
    title_en: "Late-night Karaoke Booking",
    situation_en: "You and friends book a karaoke room for 3 hours with the free drink bar.",
    role_en: "Karaoke staff",
    tone_en: "Polite + energetic",
    opening_en: "Staff asks duration, party size, and package choice.",
    ai_first_japanese: "いらっしゃいませ！何人様ですか？何時間くらいですか？",
    ai_first_romaji: "Irasshaimase! Nan-nin-sama desu ka? Nan-jikan gurai desu ka?",
    persona:
      "You are an energetic karaoke staff member in Shibuya. Use polite but lively Japanese. Ask about party size, duration, drink plan, and room size. Explain pricing and the remote control. Keep replies upbeat and concise (1-2 sentences).",
  },
  {
    id: "sc_taxi",
    emoji: "🚕",
    free: false,
    title_id: "Naik Taksi ke Stasiun Tokyo",
    situation_id: "Kamu naik taksi dari hotel ke Stasiun Tokyo pagi hari saat hujan.",
    role_id: "Supir taksi",
    tone_id: "Sopan + santai",
    opening_id: "Supir menyapa dan tanya tujuan. Jelaskan rute dan tanya waktu keberangkatan.",
    title_en: "Taxi Ride to Tokyo Station",
    situation_en: "You take a taxi from your hotel to Tokyo Station on a rainy morning.",
    role_en: "Taxi driver",
    tone_en: "Polite + relaxed",
    opening_en: "The driver greets you and asks the destination. Explain route and departure time.",
    ai_first_japanese: "おはようございます。どちらまでお送りしましょうか？",
    ai_first_romaji: "Ohayou gozaimasu. Dochira made o-okuri shimashou ka?",
    persona:
      "You are a polite Tokyo taxi driver. Use polite but relaxed Japanese. Ask destination, confirm route, mention estimated time and fare. Keep replies to 1-2 sentences. Be courteous and professional.",
  },
];

export function getScenario(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
