// Direktori kata gaul Jepang — konten SEO untuk menarik pencari "arti X bahasa jepang"
// dari anime, dorama, manga. Tiap entri jadi halaman static-friendly.

export type SlangEntry = {
  slug: string;
  jp: string;
  romaji: string;
  meaning_id: string;
  meaning_en: string;
  context_id: string;
  context_en: string;
  example_jp: string;
  example_romaji: string;
  example_id: string;
  example_en: string;
  tags: string[]; // e.g. ["anime", "casual"]
};

export const SLANG: SlangEntry[] = [
  {
    slug: "yabai",
    jp: "ヤバイ",
    romaji: "Yabai",
    meaning_id: "Gawat / Keren banget / Wow",
    meaning_en: "Crazy / Awesome / Oh no",
    context_id: "Bisa positif atau negatif tergantung nada. Anak muda pakai untuk apa saja yang ekstrem.",
    context_en: "Can be positive or negative depending on tone. Young people use it for anything extreme.",
    example_jp: "このラーメン、ヤバい!",
    example_romaji: "Kono ra-men, yabai!",
    example_id: "Ramen ini gila enaknya!",
    example_en: "This ramen is insane!",
    tags: ["anime", "casual", "viral"],
  },
  {
    slug: "sugoi",
    jp: "すごい",
    romaji: "Sugoi",
    meaning_id: "Hebat / Keren / Wow",
    meaning_en: "Amazing / Awesome",
    context_id: "Reaksi kagum sehari-hari. Versi anak perempuan: 'Sugooi~'",
    context_en: "Everyday awe reaction. Girly version: 'Sugooi~'",
    example_jp: "すごい!君、天才だね。",
    example_romaji: "Sugoi! Kimi, tensai da ne.",
    example_id: "Keren! Kamu jenius, ya.",
    example_en: "Wow! You're a genius.",
    tags: ["anime", "casual"],
  },
  {
    slug: "kawaii",
    jp: "かわいい",
    romaji: "Kawaii",
    meaning_id: "Lucu / Imut",
    meaning_en: "Cute / Adorable",
    context_id: "Kata paling ikonik dari budaya Jepang. Dipakai untuk apa saja yang manis.",
    context_en: "The most iconic Japanese word. Used for anything sweet.",
    example_jp: "その猫、超かわいい!",
    example_romaji: "Sono neko, chou kawaii!",
    example_id: "Kucing itu lucu banget!",
    example_en: "That cat is super cute!",
    tags: ["anime", "casual", "viral"],
  },
  {
    slug: "baka",
    jp: "バカ",
    romaji: "Baka",
    meaning_id: "Bodoh / Goblok",
    meaning_en: "Idiot / Stupid",
    context_id: "Bisa kasar, bisa juga manja antar teman/pasangan. 'Baka!' khas tsundere.",
    context_en: "Can be rude or playful between friends/couples. The classic tsundere 'Baka!'",
    example_jp: "もう、バカ!",
    example_romaji: "Mou, baka!",
    example_id: "Ih, bodoh!",
    example_en: "Geez, you idiot!",
    tags: ["anime", "tsundere"],
  },
  {
    slug: "daijoubu",
    jp: "大丈夫",
    romaji: "Daijoubu",
    meaning_id: "Tidak apa-apa / Aman",
    meaning_en: "It's okay / I'm fine",
    context_id: "Frasa survival paling penting. Bisa untuk menjawab 'aku baik-baik saja' atau 'tidak usah'.",
    context_en: "Most essential survival phrase. Means 'I'm fine' or 'no thanks'.",
    example_jp: "大丈夫、心配しないで。",
    example_romaji: "Daijoubu, shinpai shinaide.",
    example_id: "Aku gak apa-apa, jangan khawatir.",
    example_en: "I'm okay, don't worry.",
    tags: ["survival", "dorama"],
  },
  {
    slug: "ganbatte",
    jp: "頑張って",
    romaji: "Ganbatte",
    meaning_id: "Semangat! / Berusahalah!",
    meaning_en: "Do your best! / Good luck!",
    context_id: "Dukungan klasik sebelum ujian, pertandingan, atau tantangan apa pun.",
    context_en: "Classic encouragement before exams, matches, or any challenge.",
    example_jp: "明日のテスト、頑張って!",
    example_romaji: "Ashita no tesuto, ganbatte!",
    example_id: "Tes besok, semangat ya!",
    example_en: "Good luck on tomorrow's test!",
    tags: ["anime", "dorama", "casual"],
  },
  {
    slug: "uso",
    jp: "ウソ",
    romaji: "Uso",
    meaning_id: "Bohong! / Yang bener?",
    meaning_en: "No way! / Are you serious?",
    context_id: "Reaksi tak percaya. 'Uso!' = 'Beneran?' Bukan tuduhan bohong.",
    context_en: "Disbelief reaction. 'Uso!' = 'For real?' Not an accusation of lying.",
    example_jp: "ウソ!本当に?",
    example_romaji: "Uso! Hontou ni?",
    example_id: "Yang bener?! Serius?",
    example_en: "No way! Really?",
    tags: ["anime", "casual"],
  },
  {
    slug: "maji",
    jp: "マジ",
    romaji: "Maji",
    meaning_id: "Serius / Beneran",
    meaning_en: "Seriously / For real",
    context_id: "Versi gaul dari 'hontou'. 'Maji de?' = 'Serius?' khas anak muda.",
    context_en: "Slang version of 'hontou'. 'Maji de?' = 'Seriously?' used by youth.",
    example_jp: "マジで?信じられない!",
    example_romaji: "Maji de? Shinjirarenai!",
    example_id: "Serius? Gak nyangka!",
    example_en: "Seriously? Unbelievable!",
    tags: ["casual", "viral"],
  },
  {
    slug: "tsundere",
    jp: "ツンデレ",
    romaji: "Tsundere",
    meaning_id: "Karakter dingin-luar manis-dalam",
    meaning_en: "Cold outside, sweet inside character",
    context_id: "Arketipe anime: ngomong galak tapi sebenarnya peduli. 'Baka! Bukan untuk kamu, kok!'",
    context_en: "Anime archetype: acts harsh but actually cares. 'Baka! It's not like I made it for you!'",
    example_jp: "彼女、超ツンデレだね。",
    example_romaji: "Kanojo, chou tsundere da ne.",
    example_id: "Dia tsundere banget, ya.",
    example_en: "She's such a tsundere.",
    tags: ["anime", "otaku"],
  },
  {
    slug: "senpai",
    jp: "先輩",
    romaji: "Senpai",
    meaning_id: "Kakak kelas / Senior",
    meaning_en: "Upperclassman / Senior",
    context_id: "Panggilan untuk orang yang lebih dulu di sekolah/kerja. Meme: 'Notice me, senpai!'",
    context_en: "Term for someone ahead of you in school/work. Meme: 'Notice me, senpai!'",
    example_jp: "先輩、お疲れさまです!",
    example_romaji: "Senpai, otsukaresama desu!",
    example_id: "Kak, makasih kerja kerasnya!",
    example_en: "Senpai, good work today!",
    tags: ["anime", "school"],
  },
  {
    slug: "itadakimasu",
    jp: "いただきます",
    romaji: "Itadakimasu",
    meaning_id: "Selamat makan (sebelum makan)",
    meaning_en: "Let's eat / I receive this gratefully",
    context_id: "Diucapkan sebelum makan, tangan dirapatkan. Tanda hormat ke koki & bahan makanan.",
    context_en: "Said before eating, hands together. Respect to the chef & ingredients.",
    example_jp: "いただきまーす!",
    example_romaji: "Itadakima-su!",
    example_id: "Selamat makan!",
    example_en: "Let's eat!",
    tags: ["survival", "anime"],
  },
  {
    slug: "otsukare",
    jp: "お疲れ",
    romaji: "Otsukare",
    meaning_id: "Good job / Capek ya",
    meaning_en: "Good work / You must be tired",
    context_id: "Sapaan setelah kerja/belajar. Lebih formal: 'Otsukaresama deshita'.",
    context_en: "Greeting after work/study. More formal: 'Otsukaresama deshita'.",
    example_jp: "お疲れー!飲みに行く?",
    example_romaji: "Otsukare-! Nomi ni iku?",
    example_id: "Cape ya! Mau ngopi/minum?",
    example_en: "Good work! Wanna grab a drink?",
    tags: ["casual", "office"],
  },
  {
    slug: "mendokusai",
    jp: "面倒くさい",
    romaji: "Mendokusai",
    meaning_id: "Ribet / Males banget",
    meaning_en: "Such a hassle / Can't be bothered",
    context_id: "Keluhan favorit Shikamaru (Naruto). Untuk segala hal yang ribet/males.",
    context_en: "Shikamaru's (Naruto) favorite complaint. For anything tedious.",
    example_jp: "宿題、めんどくさい…",
    example_romaji: "Shukudai, mendokusai…",
    example_id: "PR, males banget…",
    example_en: "Homework is such a drag…",
    tags: ["anime", "casual"],
  },
  {
    slug: "moshi-moshi",
    jp: "もしもし",
    romaji: "Moshi moshi",
    meaning_id: "Halo (di telepon)",
    meaning_en: "Hello (on the phone)",
    context_id: "Sapaan khusus saat angkat telepon. Tidak dipakai tatap muka.",
    context_en: "Phone-only greeting. Never used face-to-face.",
    example_jp: "もしもし、田中です。",
    example_romaji: "Moshi moshi, Tanaka desu.",
    example_id: "Halo, ini Tanaka.",
    example_en: "Hello, this is Tanaka.",
    tags: ["survival"],
  },
  {
    slug: "sumimasen",
    jp: "すみません",
    romaji: "Sumimasen",
    meaning_id: "Maaf / Permisi / Makasih",
    meaning_en: "Sorry / Excuse me / Thanks",
    context_id: "Frasa multi-fungsi paling Jepang. Bisa minta maaf, panggil waiter, atau terima kasih.",
    context_en: "Most quintessentially Japanese multi-tool phrase. Apology, calling a waiter, or thanks.",
    example_jp: "すみません、お会計お願いします。",
    example_romaji: "Sumimasen, okaikei onegaishimasu.",
    example_id: "Permisi, minta bonnya.",
    example_en: "Excuse me, the bill please.",
    tags: ["survival"],
  },
  {
    slug: "kakkoii",
    jp: "かっこいい",
    romaji: "Kakkoii",
    meaning_id: "Keren / Cool",
    meaning_en: "Cool / Stylish",
    context_id: "Untuk orang/barang yang gaya. Versi anak muda: 'Kakkee!'",
    context_en: "For stylish people/things. Slangy version: 'Kakkee!'",
    example_jp: "その車、かっこいい!",
    example_romaji: "Sono kuruma, kakkoii!",
    example_id: "Mobil itu keren!",
    example_en: "That car is so cool!",
    tags: ["casual", "anime"],
  },
  {
    slug: "natsukashii",
    jp: "懐かしい",
    romaji: "Natsukashii",
    meaning_id: "Bikin nostalgia / Kangen masa lalu",
    meaning_en: "Nostalgic / Brings back memories",
    context_id: "Reaksi saat ketemu sesuatu dari masa kecil. Tidak ada padanan satu kata di Inggris.",
    context_en: "Reaction to something from your past. No single-word English equivalent.",
    example_jp: "この曲、懐かしい〜!",
    example_romaji: "Kono kyoku, natsukashii~!",
    example_id: "Lagu ini bikin kangen masa lalu~",
    example_en: "This song takes me back~",
    tags: ["dorama", "casual"],
  },
  {
    slug: "ittekimasu",
    jp: "行ってきます",
    romaji: "Ittekimasu",
    meaning_id: "Aku pergi dulu (& akan kembali)",
    meaning_en: "I'm leaving (and will be back)",
    context_id: "Diucapkan saat keluar rumah. Yang di rumah balas: 'Itterasshai'.",
    context_en: "Said when leaving home. Reply from home: 'Itterasshai'.",
    example_jp: "行ってきまーす!",
    example_romaji: "Ittekima-su!",
    example_id: "Aku berangkat dulu!",
    example_en: "I'm heading out!",
    tags: ["survival", "anime"],
  },
  {
    slug: "tadaima",
    jp: "ただいま",
    romaji: "Tadaima",
    meaning_id: "Aku pulang!",
    meaning_en: "I'm home!",
    context_id: "Diucapkan saat tiba di rumah. Balasannya: 'Okaeri'.",
    context_en: "Said when arriving home. Reply: 'Okaeri'.",
    example_jp: "ただいま!",
    example_romaji: "Tadaima!",
    example_id: "Aku pulang!",
    example_en: "I'm home!",
    tags: ["survival", "anime"],
  },
  {
    slug: "ureshii",
    jp: "嬉しい",
    romaji: "Ureshii",
    meaning_id: "Senang / Bahagia",
    meaning_en: "Happy / Glad",
    context_id: "Ekspresi langsung tentang perasaan senang. Beda dari 'tanoshii' (fun/asik).",
    context_en: "Direct expression of feeling happy. Different from 'tanoshii' (fun).",
    example_jp: "会えて嬉しいです。",
    example_romaji: "Aete ureshii desu.",
    example_id: "Senang bisa ketemu.",
    example_en: "Glad to meet you.",
    tags: ["dorama", "casual"],
  },
  {
    slug: "hontou",
    jp: "本当",
    romaji: "Hontou",
    meaning_id: "Beneran / Sungguh",
    meaning_en: "Really / Truly",
    context_id: "'Hontou ni?' = 'Beneran?' Versi sopan dari 'maji'.",
    context_en: "'Hontou ni?' = 'Really?' Polite version of 'maji'.",
    example_jp: "本当にありがとう。",
    example_romaji: "Hontou ni arigatou.",
    example_id: "Beneran terima kasih ya.",
    example_en: "Truly thank you.",
    tags: ["casual", "dorama"],
  },
  {
    slug: "chotto",
    jp: "ちょっと",
    romaji: "Chotto",
    meaning_id: "Sebentar / Sedikit / Tunggu dulu",
    meaning_en: "A little / Wait a sec",
    context_id: "Multi-fungsi: panggil orang ('Chotto!'), tolak halus ('Chotto…'), atau minta waktu.",
    context_en: "Multi-use: hailing ('Chotto!'), soft refusal ('Chotto…'), or asking for a moment.",
    example_jp: "ちょっと待って!",
    example_romaji: "Chotto matte!",
    example_id: "Tunggu sebentar!",
    example_en: "Hold on a sec!",
    tags: ["survival", "casual"],
  },
  {
    slug: "kimochi",
    jp: "気持ち",
    romaji: "Kimochi",
    meaning_id: "Perasaan / Enak",
    meaning_en: "Feeling / Mood",
    context_id: "Soal perasaan/sensasi fisik. 'Kimochi ii' = 'Enak banget/nyaman'.",
    context_en: "About feelings/physical sensation. 'Kimochi ii' = 'Feels good/comfy'.",
    example_jp: "温泉、気持ちいい〜!",
    example_romaji: "Onsen, kimochi ii~!",
    example_id: "Onsen, enak banget~!",
    example_en: "The hot spring feels so good~!",
    tags: ["dorama", "casual"],
  },
  {
    slug: "shouganai",
    jp: "しょうがない",
    romaji: "Shouganai",
    meaning_id: "Mau gimana lagi / Ya udahlah",
    meaning_en: "It can't be helped / Oh well",
    context_id: "Filosofi Jepang dalam satu kata. Menerima keadaan yang tak bisa diubah.",
    context_en: "Japanese philosophy in one word. Accepting what can't be changed.",
    example_jp: "雨か…しょうがないね。",
    example_romaji: "Ame ka… shouganai ne.",
    example_id: "Hujan ya… ya udah deh.",
    example_en: "Raining huh… nothing we can do.",
    tags: ["dorama", "casual"],
  },
  {
    slug: "kanpai",
    jp: "乾杯",
    romaji: "Kanpai",
    meaning_id: "Cheers! (toast)",
    meaning_en: "Cheers! (toast)",
    context_id: "Toast saat minum bersama. Wajib ada di nomikai (pesta kantor).",
    context_en: "Toast when drinking together. Mandatory at nomikai (office party).",
    example_jp: "じゃあ、乾杯!",
    example_romaji: "Jaa, kanpai!",
    example_id: "Yuk, cheers!",
    example_en: "Alright, cheers!",
    tags: ["dorama", "casual", "office"],
  },
];

export function getSlang(slug: string): SlangEntry | undefined {
  return SLANG.find((s) => s.slug === slug);
}
