/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TabelHiraganaRouteImport } from './routes/tabel-hiragana'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PanduanWisataRouteImport } from './routes/panduan-wisata'
import { Route as NamaJepangRouteImport } from './routes/nama-jepang'
import { Route as GameKanaRouteImport } from './routes/game-kana'
import { Route as FavoritRouteImport } from './routes/favorit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KamusSlangIndexRouteImport } from './routes/kamus-slang.index'
import { Route as InterviewIndexRouteImport } from './routes/interview.index'
import { Route as KamusSlangSlugRouteImport } from './routes/kamus-slang.$slug'
import { Route as InterviewScenarioIdRouteImport } from './routes/interview.$scenarioId'
import { Route as HanashiteScenarioIdRouteImport } from './routes/hanashite.$scenarioId'
import { Route as BelajarReviewRouteImport } from './routes/belajar.review'
import { Route as BelajarSessionIdRouteImport } from './routes/belajar.$sessionId'
import { Route as ApiNamaJepangRouteImport } from './routes/api/nama-jepang'
import { Route as ApiHanashiteRouteImport } from './routes/api/hanashite'
import { Route as ApiActivateProRouteImport } from './routes/api/activate-pro'
import { Route as BelajarLevelLevelIdRouteImport } from './routes/belajar.level.$levelId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsReconcileRouteImport } from './routes/api/public/payments/reconcile'
import { Route as ApiPublicHooksDailyStreakPushRouteImport } from './routes/api/public/hooks/daily-streak-push'

const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelHiraganaRoute = TabelHiraganaRouteImport.update({
  id: '/tabel-hiragana',
  path: '/tabel-hiragana',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanWisataRoute = PanduanWisataRouteImport.update({
  id: '/panduan-wisata',
  path: '/panduan-wisata',
  getParentRoute: () => rootRouteImport,
} as any)
const NamaJepangRoute = NamaJepangRouteImport.update({
  id: '/nama-jepang',
  path: '/nama-jepang',
  getParentRoute: () => rootRouteImport,
} as any)
const GameKanaRoute = GameKanaRouteImport.update({
  id: '/game-kana',
  path: '/game-kana',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritRoute = FavoritRouteImport.update({
  id: '/favorit',
  path: '/favorit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamusSlangIndexRoute = KamusSlangIndexRouteImport.update({
  id: '/kamus-slang/',
  path: '/kamus-slang/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIndexRoute = InterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamusSlangSlugRoute = KamusSlangSlugRouteImport.update({
  id: '/kamus-slang/$slug',
  path: '/kamus-slang/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewScenarioIdRoute = InterviewScenarioIdRouteImport.update({
  id: '/interview/$scenarioId',
  path: '/interview/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const HanashiteScenarioIdRoute = HanashiteScenarioIdRouteImport.update({
  id: '/hanashite/$scenarioId',
  path: '/hanashite/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarReviewRoute = BelajarReviewRouteImport.update({
  id: '/belajar/review',
  path: '/belajar/review',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarSessionIdRoute = BelajarSessionIdRouteImport.update({
  id: '/belajar/$sessionId',
  path: '/belajar/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNamaJepangRoute = ApiNamaJepangRouteImport.update({
  id: '/api/nama-jepang',
  path: '/api/nama-jepang',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHanashiteRoute = ApiHanashiteRouteImport.update({
  id: '/api/hanashite',
  path: '/api/hanashite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivateProRoute = ApiActivateProRouteImport.update({
  id: '/api/activate-pro',
  path: '/api/activate-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarLevelLevelIdRoute = BelajarLevelLevelIdRouteImport.update({
  id: '/belajar/level/$levelId',
  path: '/belajar/level/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsReconcileRoute =
  ApiPublicPaymentsReconcileRouteImport.update({
    id: '/api/public/payments/reconcile',
    path: '/api/public/payments/reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyStreakPushRoute =
  ApiPublicHooksDailyStreakPushRouteImport.update({
    id: '/api/public/hooks/daily-streak-push',
    path: '/api/public/hooks/daily-streak-push',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorit': typeof FavoritRoute
  '/game-kana': typeof GameKanaRoute
  '/nama-jepang': typeof NamaJepangRoute
  '/panduan-wisata': typeof PanduanWisataRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/review': typeof ReviewRoute
  '/riwayat': typeof RiwayatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabel-hiragana': typeof TabelHiraganaRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/translate': typeof TranslateRoute
  '/api/activate-pro': typeof ApiActivateProRoute
  '/api/hanashite': typeof ApiHanashiteRoute
  '/api/nama-jepang': typeof ApiNamaJepangRoute
  '/belajar/$sessionId': typeof BelajarSessionIdRoute
  '/belajar/review': typeof BelajarReviewRoute
  '/hanashite/$scenarioId': typeof HanashiteScenarioIdRoute
  '/interview/$scenarioId': typeof InterviewScenarioIdRoute
  '/kamus-slang/$slug': typeof KamusSlangSlugRoute
  '/interview/': typeof InterviewIndexRoute
  '/kamus-slang/': typeof KamusSlangIndexRoute
  '/belajar/level/$levelId': typeof BelajarLevelLevelIdRoute
  '/api/public/hooks/daily-streak-push': typeof ApiPublicHooksDailyStreakPushRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorit': typeof FavoritRoute
  '/game-kana': typeof GameKanaRoute
  '/nama-jepang': typeof NamaJepangRoute
  '/panduan-wisata': typeof PanduanWisataRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/review': typeof ReviewRoute
  '/riwayat': typeof RiwayatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabel-hiragana': typeof TabelHiraganaRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/translate': typeof TranslateRoute
  '/api/activate-pro': typeof ApiActivateProRoute
  '/api/hanashite': typeof ApiHanashiteRoute
  '/api/nama-jepang': typeof ApiNamaJepangRoute
  '/belajar/$sessionId': typeof BelajarSessionIdRoute
  '/belajar/review': typeof BelajarReviewRoute
  '/hanashite/$scenarioId': typeof HanashiteScenarioIdRoute
  '/interview/$scenarioId': typeof InterviewScenarioIdRoute
  '/kamus-slang/$slug': typeof KamusSlangSlugRoute
  '/interview': typeof InterviewIndexRoute
  '/kamus-slang': typeof KamusSlangIndexRoute
  '/belajar/level/$levelId': typeof BelajarLevelLevelIdRoute
  '/api/public/hooks/daily-streak-push': typeof ApiPublicHooksDailyStreakPushRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/favorit': typeof FavoritRoute
  '/game-kana': typeof GameKanaRoute
  '/nama-jepang': typeof NamaJepangRoute
  '/panduan-wisata': typeof PanduanWisataRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund': typeof RefundRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/review': typeof ReviewRoute
  '/riwayat': typeof RiwayatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tabel-hiragana': typeof TabelHiraganaRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/translate': typeof TranslateRoute
  '/api/activate-pro': typeof ApiActivateProRoute
  '/api/hanashite': typeof ApiHanashiteRoute
  '/api/nama-jepang': typeof ApiNamaJepangRoute
  '/belajar/$sessionId': typeof BelajarSessionIdRoute
  '/belajar/review': typeof BelajarReviewRoute
  '/hanashite/$scenarioId': typeof HanashiteScenarioIdRoute
  '/interview/$scenarioId': typeof InterviewScenarioIdRoute
  '/kamus-slang/$slug': typeof KamusSlangSlugRoute
  '/interview/': typeof InterviewIndexRoute
  '/kamus-slang/': typeof KamusSlangIndexRoute
  '/belajar/level/$levelId': typeof BelajarLevelLevelIdRoute
  '/api/public/hooks/daily-streak-push': typeof ApiPublicHooksDailyStreakPushRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/favorit'
    | '/game-kana'
    | '/nama-jepang'
    | '/panduan-wisata'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/refund'
    | '/refund-policy'
    | '/review'
    | '/riwayat'
    | '/sitemap.xml'
    | '/tabel-hiragana'
    | '/terms'
    | '/terms-of-service'
    | '/translate'
    | '/api/activate-pro'
    | '/api/hanashite'
    | '/api/nama-jepang'
    | '/belajar/$sessionId'
    | '/belajar/review'
    | '/hanashite/$scenarioId'
    | '/interview/$scenarioId'
    | '/kamus-slang/$slug'
    | '/interview/'
    | '/kamus-slang/'
    | '/belajar/level/$levelId'
    | '/api/public/hooks/daily-streak-push'
    | '/api/public/payments/reconcile'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/favorit'
    | '/game-kana'
    | '/nama-jepang'
    | '/panduan-wisata'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/refund'
    | '/refund-policy'
    | '/review'
    | '/riwayat'
    | '/sitemap.xml'
    | '/tabel-hiragana'
    | '/terms'
    | '/terms-of-service'
    | '/translate'
    | '/api/activate-pro'
    | '/api/hanashite'
    | '/api/nama-jepang'
    | '/belajar/$sessionId'
    | '/belajar/review'
    | '/hanashite/$scenarioId'
    | '/interview/$scenarioId'
    | '/kamus-slang/$slug'
    | '/interview'
    | '/kamus-slang'
    | '/belajar/level/$levelId'
    | '/api/public/hooks/daily-streak-push'
    | '/api/public/payments/reconcile'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/favorit'
    | '/game-kana'
    | '/nama-jepang'
    | '/panduan-wisata'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/refund'
    | '/refund-policy'
    | '/review'
    | '/riwayat'
    | '/sitemap.xml'
    | '/tabel-hiragana'
    | '/terms'
    | '/terms-of-service'
    | '/translate'
    | '/api/activate-pro'
    | '/api/hanashite'
    | '/api/nama-jepang'
    | '/belajar/$sessionId'
    | '/belajar/review'
    | '/hanashite/$scenarioId'
    | '/interview/$scenarioId'
    | '/kamus-slang/$slug'
    | '/interview/'
    | '/kamus-slang/'
    | '/belajar/level/$levelId'
    | '/api/public/hooks/daily-streak-push'
    | '/api/public/payments/reconcile'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FavoritRoute: typeof FavoritRoute
  GameKanaRoute: typeof GameKanaRoute
  NamaJepangRoute: typeof NamaJepangRoute
  PanduanWisataRoute: typeof PanduanWisataRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundRoute: typeof RefundRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReviewRoute: typeof ReviewRoute
  RiwayatRoute: typeof RiwayatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TabelHiraganaRoute: typeof TabelHiraganaRoute
  TermsRoute: typeof TermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TranslateRoute: typeof TranslateRoute
  ApiActivateProRoute: typeof ApiActivateProRoute
  ApiHanashiteRoute: typeof ApiHanashiteRoute
  ApiNamaJepangRoute: typeof ApiNamaJepangRoute
  BelajarSessionIdRoute: typeof BelajarSessionIdRoute
  BelajarReviewRoute: typeof BelajarReviewRoute
  HanashiteScenarioIdRoute: typeof HanashiteScenarioIdRoute
  InterviewScenarioIdRoute: typeof InterviewScenarioIdRoute
  KamusSlangSlugRoute: typeof KamusSlangSlugRoute
  InterviewIndexRoute: typeof InterviewIndexRoute
  KamusSlangIndexRoute: typeof KamusSlangIndexRoute
  BelajarLevelLevelIdRoute: typeof BelajarLevelLevelIdRoute
  ApiPublicHooksDailyStreakPushRoute: typeof ApiPublicHooksDailyStreakPushRoute
  ApiPublicPaymentsReconcileRoute: typeof ApiPublicPaymentsReconcileRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabel-hiragana': {
      id: '/tabel-hiragana'
      path: '/tabel-hiragana'
      fullPath: '/tabel-hiragana'
      preLoaderRoute: typeof TabelHiraganaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan-wisata': {
      id: '/panduan-wisata'
      path: '/panduan-wisata'
      fullPath: '/panduan-wisata'
      preLoaderRoute: typeof PanduanWisataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nama-jepang': {
      id: '/nama-jepang'
      path: '/nama-jepang'
      fullPath: '/nama-jepang'
      preLoaderRoute: typeof NamaJepangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-kana': {
      id: '/game-kana'
      path: '/game-kana'
      fullPath: '/game-kana'
      preLoaderRoute: typeof GameKanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorit': {
      id: '/favorit'
      path: '/favorit'
      fullPath: '/favorit'
      preLoaderRoute: typeof FavoritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamus-slang/': {
      id: '/kamus-slang/'
      path: '/kamus-slang'
      fullPath: '/kamus-slang/'
      preLoaderRoute: typeof KamusSlangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/': {
      id: '/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamus-slang/$slug': {
      id: '/kamus-slang/$slug'
      path: '/kamus-slang/$slug'
      fullPath: '/kamus-slang/$slug'
      preLoaderRoute: typeof KamusSlangSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$scenarioId': {
      id: '/interview/$scenarioId'
      path: '/interview/$scenarioId'
      fullPath: '/interview/$scenarioId'
      preLoaderRoute: typeof InterviewScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hanashite/$scenarioId': {
      id: '/hanashite/$scenarioId'
      path: '/hanashite/$scenarioId'
      fullPath: '/hanashite/$scenarioId'
      preLoaderRoute: typeof HanashiteScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar/review': {
      id: '/belajar/review'
      path: '/belajar/review'
      fullPath: '/belajar/review'
      preLoaderRoute: typeof BelajarReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar/$sessionId': {
      id: '/belajar/$sessionId'
      path: '/belajar/$sessionId'
      fullPath: '/belajar/$sessionId'
      preLoaderRoute: typeof BelajarSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nama-jepang': {
      id: '/api/nama-jepang'
      path: '/api/nama-jepang'
      fullPath: '/api/nama-jepang'
      preLoaderRoute: typeof ApiNamaJepangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hanashite': {
      id: '/api/hanashite'
      path: '/api/hanashite'
      fullPath: '/api/hanashite'
      preLoaderRoute: typeof ApiHanashiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activate-pro': {
      id: '/api/activate-pro'
      path: '/api/activate-pro'
      fullPath: '/api/activate-pro'
      preLoaderRoute: typeof ApiActivateProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar/level/$levelId': {
      id: '/belajar/level/$levelId'
      path: '/belajar/level/$levelId'
      fullPath: '/belajar/level/$levelId'
      preLoaderRoute: typeof BelajarLevelLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/reconcile': {
      id: '/api/public/payments/reconcile'
      path: '/api/public/payments/reconcile'
      fullPath: '/api/public/payments/reconcile'
      preLoaderRoute: typeof ApiPublicPaymentsReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-streak-push': {
      id: '/api/public/hooks/daily-streak-push'
      path: '/api/public/hooks/daily-streak-push'
      fullPath: '/api/public/hooks/daily-streak-push'
      preLoaderRoute: typeof ApiPublicHooksDailyStreakPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FavoritRoute: FavoritRoute,
  GameKanaRoute: GameKanaRoute,
  NamaJepangRoute: NamaJepangRoute,
  PanduanWisataRoute: PanduanWisataRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundRoute: RefundRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReviewRoute: ReviewRoute,
  RiwayatRoute: RiwayatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TabelHiraganaRoute: TabelHiraganaRoute,
  TermsRoute: TermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TranslateRoute: TranslateRoute,
  ApiActivateProRoute: ApiActivateProRoute,
  ApiHanashiteRoute: ApiHanashiteRoute,
  ApiNamaJepangRoute: ApiNamaJepangRoute,
  BelajarSessionIdRoute: BelajarSessionIdRoute,
  BelajarReviewRoute: BelajarReviewRoute,
  HanashiteScenarioIdRoute: HanashiteScenarioIdRoute,
  InterviewScenarioIdRoute: InterviewScenarioIdRoute,
  KamusSlangSlugRoute: KamusSlangSlugRoute,
  InterviewIndexRoute: InterviewIndexRoute,
  KamusSlangIndexRoute: KamusSlangIndexRoute,
  BelajarLevelLevelIdRoute: BelajarLevelLevelIdRoute,
  ApiPublicHooksDailyStreakPushRoute: ApiPublicHooksDailyStreakPushRoute,
  ApiPublicPaymentsReconcileRoute: ApiPublicPaymentsReconcileRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
