/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as FavoritRouteImport } from './routes/favorit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiActivateProRouteImport } from './routes/api/activate-pro'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritRoute = FavoritRouteImport.update({
  id: '/favorit',
  path: '/favorit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivateProRoute = ApiActivateProRouteImport.update({
  id: '/api/activate-pro',
  path: '/api/activate-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorit': typeof FavoritRoute
  '/review': typeof ReviewRoute
  '/riwayat': typeof RiwayatRoute
  '/api/activate-pro': typeof ApiActivateProRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorit': typeof FavoritRoute
  '/review': typeof ReviewRoute
  '/riwayat': typeof RiwayatRoute
  '/api/activate-pro': typeof ApiActivateProRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorit': typeof FavoritRoute
  '/review': typeof ReviewRoute
  '/riwayat': typeof RiwayatRoute
  '/api/activate-pro': typeof ApiActivateProRoute
  '/api/translate': typeof ApiTranslateRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/favorit'
    | '/review'
    | '/riwayat'
    | '/api/activate-pro'
    | '/api/translate'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/favorit'
    | '/review'
    | '/riwayat'
    | '/api/activate-pro'
    | '/api/translate'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/favorit'
    | '/review'
    | '/riwayat'
    | '/api/activate-pro'
    | '/api/translate'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FavoritRoute: typeof FavoritRoute
  ReviewRoute: typeof ReviewRoute
  RiwayatRoute: typeof RiwayatRoute
  ApiActivateProRoute: typeof ApiActivateProRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorit': {
      id: '/favorit'
      path: '/favorit'
      fullPath: '/favorit'
      preLoaderRoute: typeof FavoritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activate-pro': {
      id: '/api/activate-pro'
      path: '/api/activate-pro'
      fullPath: '/api/activate-pro'
      preLoaderRoute: typeof ApiActivateProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FavoritRoute: FavoritRoute,
  ReviewRoute: ReviewRoute,
  RiwayatRoute: RiwayatRoute,
  ApiActivateProRoute: ApiActivateProRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
